name: E2E

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: npm install
      run: npm install

    - name: npm test e2e
      run: |
        git config --global user.email "devops@socketsupply.co"
        git config --global user.name "Socket Supply, Co - Github Actions"
        ## @TODO(jwerle): change branch when stable
        git clone --branch headless --depth 1 git@github.com:socketsupply/socket-sdk.git
        cd socket-sdk
        ./bin/install.sh
        cd ..
        npm install
        npm run test:e2e
      env:
        CI: true
